"""update user profile to include date joined

Revision ID: 28081beea797
Revises: c988a0de862e
Create Date: 2021-03-11 12:53:52.871530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28081beea797'
down_revision = 'c988a0de862e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_joined', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_joined')
    # ### end Alembic commands ###
